[font]
size = 12.0

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
opacity = 0.9

[window.padding]
x = 4 
y = 2 

# links open only with ctrl+click (from https://github.com/alacritty/alacritty/issues/5246)
# xdg-open comes from xdg-utils
[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
